openapi: "3.0.2"
info:
  title: "API Title"
  version: "1.0"
paths:
  /hello:
    get:
      tags:
        - Test
      summary: Gets hello test string
      description: >
      responses:
        '200':
          description: OK